//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BOOK
    {
        public TBL_BOOK()
        {
            this.TBL_RESRVATION = new HashSet<TBL_RESRVATION>();
        }
    
        public int book_id { get; set; }
        public string title { get; set; }
        public string photo { get; set; }
        public int numofcopies { get; set; }
        public int isbn { get; set; }
    
        public virtual ICollection<TBL_RESRVATION> TBL_RESRVATION { get; set; }
    }
}
