//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER
    {
        public TBL_USER()
        {
            this.TBL_RESRVATION = new HashSet<TBL_RESRVATION>();
        }
    
        public int user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<TBL_RESRVATION> TBL_RESRVATION { get; set; }
    }
}
