//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RESRVATION
    {
        public int reservation_id { get; set; }
        public int book_id { get; set; }
        public int user_id { get; set; }
    
        public virtual TBL_BOOK TBL_BOOK { get; set; }
        public virtual TBL_USER TBL_USER { get; set; }
    }
}
